version: "3.7"

services:
  app:
    image: paulomarcio/php-fpm-7.3
    container_name: bnb-bank-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bnbbank
    restart: unless-stopped

  nginx:
    image: nginx:1.17-alpine
    container_name: bnb-bank-web
    ports:
      - "${PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bnbbank
    restart: unless-stopped

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: bnb-bank-db
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - bnbbank

networks:
  bnbbank:
    name: bnbbank
    driver: bridge
