version: "3.7"

services:
  app:
    image: paulomarcio/php-fpm-7.3
    container_name: bnb-bank-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bnbbank
    restart: unless-stopped

  nginx:
    image: nginx:1.17-alpine
    container_name: bnb-bank-web
    ports:
      - "${PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bnbbank
    restart: unless-stopped

  db:
    image: postgres
    container_name: bnb-bank-db
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - bnbbank

networks:
  bnbbank:
    name: bnbbank
    driver: bridge
